### PR TITLE
javdb enable user login cookies

### PR DESCRIPTION
**Pull request by lededev**
支持通过Chrome浏览器访问javdb9.com网站，并且进行用户登录后，获取仅用户登录时才能访问的页面信息，示例番号：FC2-735670 https://javdb9.com/v/vO8Mn
在EXE执行文件的当前目录(与config.ini相同目录)建立cookies文件`javdb9.json`，内容如下（以下各字段的数值部分数据为虚构，请按自己账户的真实登录数据填写）：
```json
{
    "over18":"1",
    "redirect_to":"%2Fv%2FvO8Mn",
    "remember_me_token":"cbJdeaFpbHMiOnsibWVzc2FnZSI6IklrNVJjbTAzZFVSRVEpUVFhOVU0yNXhJZz09IiwiZXhwIjoiMjAyMS0wNS0xNVQxMzoyODoxNy4wMDBaIiwicHVyIjoiY29va2llLnJlbWVtYmVylX3Rva2VuIn19--a713d411b635889bff3fe3",
    "_jdb_session":"asddefqfwfwwrfdsdaAmqKj1%2FvOrDQP4b7h%2BvGp7brvIShi2Y%2FHBUr%2BklApk06TfhBOK3g5gRImZzoi49GINH%2FK49o3W%2FX64ugBiUAcudN9b27Mg6Ohu%2Bx9Z7A4bbqmqCt7XR%2jMcdDG5czoYHJCPIPZQFU28Gd7Awc2jc5FM5CoIgSRyaYDy9ulTO7DlavxoNL%2F6OFEL%2FyaA6XUYTB2Gs1kpPiUDqwi854mo5%2FrNxMhTeBK%2BjXciazMtN5KlE5JIOfiWAjNrnx7SV3Hj%2FqPNxRxXFQyEwHr5TZa0Vk1%2FjbwWQ0wcIFfh%2FMLwwqKydAh%2FLndc%2Bmdv3e%2FJ%2BiL2--xhqYnMyVRlxJaN--u7n7tZtPd4kIaEbg%3D%3D",
    "locale":"zh",
    "__cfduid":"dee27116d98c2342a5cabc1fe0e7c2f3c91620479752",
    "theme":"auto"
}
```
通过浏览器插件(CookieBro或EdittThisCookie)或者直接在地址栏网站链接信息处都可以复制或者导出cookie内容（注意：需要先在Chrome浏览器中访问 https://javdb9.com/login 勾选保持七天登录状态，并输入用户名、密码、图形验证码成功进行页面用户登录后，cookie内容才是有效登录数据），并填写到以上json文件的相应字段中。

### CODE REVIEW

**Comment by lededev** [comment]
fix issue https://github.com/yoshiko2/AV_Data_Capture/issues/464 https://github.com/yoshiko2/AV_Data_Capture/issues/446 https://github.com/yoshiko2/AV_Data_Capture/issues/429 https://github.com/yoshiko2/AV_Data_Capture/issues/384

**Comment by lededev** [comment]
Windows 10 x64, Vivaldi 浏览器下，自动解密浏览器Cookies文件并生成javdb9.json文件的工具程序。如果改为用Chrome浏览器需要修改程序中的浏览器用户数据路径BROWSER_PROFILE_PATH。
```python
# Based on:
# 	https://gist.github.com/DakuTree/98c8362fb424351b803e
# 	https://gist.github.com/jordan-wright/5770442
# 	https://gist.github.com/DakuTree/428e5b737306937628f2944fbfdc4ffc
# 	https://stackoverflow.com/questions/60416350/chrome-80-how-to-decode-cookies
# 	https://stackoverflow.com/questions/43987779/python-module-crypto-cipher-aes-has-no-attribute-mode-ccm-even-though-pycry

import os
import json
import base64
import sqlite3
from shutil import copyfile

# python.exe -m pip install pypiwin32
import win32crypt
# python.exe -m pip install pycryptodomex
from Cryptodome.Cipher import AES

#BROWSER_PROFILE_PATH = os.getenv("APPDATA") + "/../Local/Google/Chrome/User Data"
BROWSER_PROFILE_PATH = os.getenv("APPDATA") + "/../Local/Vivaldi/User Data"

# Copy Cookies and Local State to current folder
copyfile(BROWSER_PROFILE_PATH + "/Default/Cookies", './Cookies')

# Load encryption key
encrypted_key = None
with open(BROWSER_PROFILE_PATH + "/Local State", 'r') as file:
	encrypted_key = json.loads(file.read())['os_crypt']['encrypted_key']
encrypted_key = base64.b64decode(encrypted_key)
encrypted_key = encrypted_key[5:]
decrypted_key = win32crypt.CryptUnprotectData(encrypted_key, None, None, None, 0)[1]


# Connect to the Database
conn = sqlite3.connect('./Cookies')
cursor = conn.cursor()

# Get the results
cursor.execute('SELECT host_key, name, value, encrypted_value FROM cookies')
for host_key, name, value, encrypted_value in cursor.fetchall():
	# Decrypt the encrypted_value
	try:
		# Try to decrypt as AES (2020 method)
		cipher = AES.new(decrypted_key, AES.MODE_GCM, nonce=encrypted_value[3:3+12])
		decrypted_value = cipher.decrypt_and_verify(encrypted_value[3+12:-16], encrypted_value[-16:])
	except:
		# If failed try with the old method
		decrypted_value = win32crypt.CryptUnprotectData(encrypted_value, None, None, None, 0)[1].decode('utf-8') or value or 0

	# Update the cookies with the decrypted value
	# This also makes all session cookies persistent
	cursor.execute('\
		UPDATE cookies SET value = ?, has_expires = 1, expires_utc = 99999999999999999, is_persistent = 1, is_secure = 0\
		WHERE host_key = ?\
		AND name = ?',
		(decrypted_value, host_key, name));

conn.commit()
conn.close()

# Export javdb9.com cookies to javdb9.json
conn = sqlite3.connect('./Cookies')
cursor = conn.cursor()
cursor.execute('SELECT name, value FROM cookies WHERE host_key LIKE "%javdb9.com"')
jsonfile = open('javdb9.json', mode='w')
jsonfile.write("{\n")
for name, value in cursor.fetchall():
        jsonfile.write('"' + str(name) + '":"' + value.decode("utf-8") + '",\n')
jsonfile.write("}\n")
jsonfile.close()
conn.close()
```

**Comment by xingfanxia** [comment]
> Windows 10 x64, Vivaldi 浏览器下，自动解密浏览器Cookies文件并生成javdb9.json文件的工具程序。如果改为用Chrome浏览器需要修改程序中的浏览器用户数据路径BROWSER_PROFILE_PATH。
> 不会编译的用户可以在[这里](https://github.com/lededev/AV_Data_Capture/releases/tag/pre-4.6.3)下载已经编译的执行文件压缩包export_javdb9_from_chrome.7z，以及对应功能的AV_Data_Capture_Windows_x64-v4.6.3c-private.7z
> 
> ```python
> # Based on:
> # 	https://gist.github.com/DakuTree/98c8362fb424351b803e
> # 	https://gist.github.com/jordan-wright/5770442
> # 	https://gist.github.com/DakuTree/428e5b737306937628f2944fbfdc4ffc
> # 	https://stackoverflow.com/questions/60416350/chrome-80-how-to-decode-cookies
> # 	https://stackoverflow.com/questions/43987779/python-module-crypto-cipher-aes-has-no-attribute-mode-ccm-even-though-pycry
> 
> import os
> import json
> import base64
> import sqlite3
> from shutil import copyfile
> 
> # python.exe -m pip install pypiwin32
> import win32crypt
> # python.exe -m pip install pycryptodomex
> from Cryptodome.Cipher import AES
> 
> #BROWSER_PROFILE_PATH = os.getenv("APPDATA") + "/../Local/Google/Chrome/User Data"
> BROWSER_PROFILE_PATH = os.getenv("APPDATA") + "/../Local/Vivaldi/User Data"
> 
> # Copy Cookies and Local State to current folder
> copyfile(BROWSER_PROFILE_PATH + "/Default/Cookies", './Cookies')
> 
> # Load encryption key
> encrypted_key = None
> with open(BROWSER_PROFILE_PATH + "/Local State", 'r') as file:
> 	encrypted_key = json.loads(file.read())['os_crypt']['encrypted_key']
> encrypted_key = base64.b64decode(encrypted_key)
> encrypted_key = encrypted_key[5:]
> decrypted_key = win32crypt.CryptUnprotectData(encrypted_key, None, None, None, 0)[1]
> 
> 
> # Connect to the Database
> conn = sqlite3.connect('./Cookies')
> cursor = conn.cursor()
> 
> # Get the results
> cursor.execute('SELECT host_key, name, value, encrypted_value FROM cookies')
> for host_key, name, value, encrypted_value in cursor.fetchall():
> 	# Decrypt the encrypted_value
> 	try:
> 		# Try to decrypt as AES (2020 method)
> 		cipher = AES.new(decrypted_key, AES.MODE_GCM, nonce=encrypted_value[3:3+12])
> 		decrypted_value = cipher.decrypt_and_verify(encrypted_value[3+12:-16], encrypted_value[-16:])
> 	except:
> 		# If failed try with the old method
> 		decrypted_value = win32crypt.CryptUnprotectData(encrypted_value, None, None, None, 0)[1].decode('utf-8') or value or 0
> 
> 	# Update the cookies with the decrypted value
> 	# This also makes all session cookies persistent
> 	cursor.execute('\
> 		UPDATE cookies SET value = ?, has_expires = 1, expires_utc = 99999999999999999, is_persistent = 1, is_secure = 0\
> 		WHERE host_key = ?\
> 		AND name = ?',
> 		(decrypted_value, host_key, name));
> 
> conn.commit()
> conn.close()
> 
> # Export javdb9.com cookies to javdb9.json
> conn = sqlite3.connect('./Cookies')
> cursor = conn.cursor()
> cursor.execute('SELECT name, value FROM cookies WHERE host_key LIKE "%javdb9.com"')
> jsonfile = open('javdb9.json', mode='w')
> jsonfile.write("{\n")
> lines = 0
> last_name = ''
> last_value = ''
> for name, value in cursor.fetchall():
>         lines = lines + 1
>         if lines > 1:
>                 jsonfile.write('"' + last_name + '":"' + last_value + '",\n')
>         last_name = str(name)
>         last_value = value.decode("utf-8")
> conn.close()
> if lines > 0:
>         jsonfile.write('"' + last_name + '":"' + last_value + '"\n')
> jsonfile.write("}\n")
> jsonfile.close()
> os.remove('./Cookies')
> ```

这个script python3.8 跑完是空的

**Comment by xjc1119** [comment]
cfduid是啥？导出只有cf_bm。redirect_to又是啥？压根没这字段

**Comment by shirogane5687** [comment]
同上，死活找不到cfduid啊，哭了

**Comment by gmy771810930** [comment]
话说能不能弄个微软EDGE浏览器用的

**Comment by lededev** [comment]
> 话说能不能弄个微软EDGE浏览器用的

取消EDGE那个路径变量的注释，然后直接执行或者用pyinstaller编译后执行。

https://github.com/yoshiko2/Movie_Data_Capture/issues/504#issuecomment-939224081

**Pull request merged**
